services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Quellenform\Iconpack\:
    resource: '../Classes/*'

  Quellenform\Iconpack\EventListener\IconpackGetExternalPlugins:
    tags:
      - name: event.listener
        identifier: 'Quellenform/Iconpack/GetExternalPlugins'
        event: TYPO3\CMS\RteCKEditor\Form\Element\Event\BeforeGetExternalPluginsEvent

  Quellenform\Iconpack\EventListener\IconpackPrepareConfigurationForEditor:
    tags:
      - name: event.listener
        identifier: 'Quellenform/Iconpack/PrepareConfigurationForEditor'
        event: TYPO3\CMS\RteCKEditor\Form\Element\Event\BeforePrepareConfigurationForEditorEvent

  Quellenform\Iconpack\IconpackFactory:
    arguments:
      $iconpackCache: '@Quellenform\Iconpack\IconpackCache'
      $IconpackRegistry: '@Quellenform\Iconpack\IconpackRegistry'
    public: true
    shared: true

  Quellenform\Iconpack\Html\IconpackHtmlParser:
    arguments:
      $iconpackFactory: '@Quellenform\Iconpack\IconpackFactory'
    public: true
    shared: true
